version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Specify labels for pull requests
    labels:
      - "dependencies"
      - "npm"
    # Limit the number of open pull requests for version updates
    open-pull-requests-limit: 10
    # Set version update strategy
    versioning-strategy: auto
    # Group all minor and patch updates together
    groups:
      dependencies:
        patterns:
          - "*"
    # Allow up-to-date branches to be rebased
    rebase-strategy: "auto"
    # Specify the version update target
    target-branch: "main"
    # Set reviewers for the pull requests
    reviewers:
      - "REPLACE_WITH_YOUR_GITHUB_USERNAME" 